### ISSUE TITLE
Fla cannot be compiled under iOS.

### ISSUE THREAD

**Issue by zxl777** [fluam/fla#2]
The test is beautiful under Android, but it cannot be compiled under iOS.

This file fla-1.0.3/pubspec.yaml  has a problem with the latest flutter.
I changed it a bit to successfully execute "flutter pub get"

But in the end, the xcode build still failed, and I couldn't solve the error.

```
name: fla
description: A new Flutter project.

publish_to: "none" # Remove this line if you wish to publish to pub.dev
version: 1.0.0


environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

core:
    git: https://github.com/fluam/core.git

dev_dependencies:
  pedantic: ^1.8.0
  test: ^1.6.0
  flutter_launcher_icons: ^0.8.0

flutter_icons:
  android: true
  ios: true
flutter:
  uses-material-design: true

```
